---
title: "TrabalhoFinal2"
output: html_document
date: "2023-05-26"
---

```{r}
#### PACOTES ########################################################
library(shiny)
library(tidyverse)
library(patchwork)
library(bslib)
library(gridExtra)
library(rugarch)
library(parallel)
library(yfR)
library(dygraphs)
library(lubridate)
library(shinyjs)
library(shinydashboard)
library(shinymeta)
library(shinyWidgets)
library(shinythemes)
library(xts)
library(reactable)
library(glue)
library(feasts)
library(keys)
library(fGarch)
```

```{r}
#### BAIXAR E FORMATAR A SERIE ##################################################################
get_data = function(tickers = "MSFT34.SA", first_date = "2013-01-01",
                    last_date = (Sys.Date())){
  data = yf_get(tickers, first_date, last_date)
  data = na.omit(data[,c(2,8,9)])
  colnames(data) = c("date", "adjusted", "ret_adjusted")
  return(data)
}
#### GERAR GRAFICO INTERATIVO (DYGRAPHS) ########################################################
get_graph_main = function(data, way = "adj"){
  if(way == "adj"){
    don = xts(x = data$adjusted, order.by = data$date)
  }
  if(way == "ret"){
    don = xts(x = data$ret_adjusted, order.by = data$date)
  }
  p <- dygraph(don) %>%
    dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.1, drawGrid = FALSE, colors = "#33C481") %>%
    dyRangeSelector() %>%
    dyCrosshair(direction = "vertical") %>%
    dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 1, hideOnMouseOut = FALSE)  %>%
    dySeries("V1", label = "Price")
  return(p)
}
#### CONSEGUIR AS PREVISÕES DO MODELO ############################################################

decomposicao_aditiva <- function(dados, mMM, n_saz, y, h){
  #mMM é o período das médias móveis
  # nsaz é o período sazonal considerado
  # y é o index da variável resposta
  dados["y"] <- dados[y]
  Tend <- rep(NA, length.out = nrow(dados))
  if(mMM%%2 == 0){
    k <- mMM/2
    # se for par
    for(i in (k+1):(nrow(dados)-k)){
      Tend[i] <- (dados[i-k,"y"]+dados[i+k,"y"])/(2*mMM)+sum(dados[(i-k+1):(i+k-1),"y"])/mMM
      Tend <- do.call(rbind,Tend)
    }
  }else{
    # mMM ímpar
    k <- (mMM-1)/2
    # se for par
    for(i in (k+1):(nrow(dados)-k)){
      Tend[[i]] <- sum(dados[(i-k):(i+k),"y"])/mMM
    }
  }
  if(nrow(dados)%%n_saz == 0){
  saz_aux <- rep(1:n_saz, nrow(dados)%/%n_saz)
  }else{
  saz_aux <-c(rep(1:n_saz, nrow(dados)%/%n_saz),1:(nrow(dados)%%n_saz))
    }
  dados <- data.frame("y" = dados["y"], "tend" = Tend,
                      "saz" = saz_aux,
                      "y_st" = dados["y"]-Tend)
  colnames(dados) <- c(y, "tend", "saz", "y_st")
  sazon <- dados %>% group_by(saz) %>% summarise('ef_saz' = mean(y_st, na.rm = T))
  sazon$ef_saz <- sazon$ef_saz - mean(sazon$ef_saz)
  dados <- inner_join(dados, sazon, by = "saz") %>% mutate(R = y_st - ef_saz)
  # Predição
  dados_sem_na <- dados %>% filter(!is.na(tend))
  saz_predizer <- rep(dados[nrow(dados),"saz"],h)
  saz_predizer <- saz_predizer +1:h
  saz_predizer <- saz_predizer%%n_saz
  s_hat <- dados_sem_na %>% filter(saz %in% saz_predizer) %>% tail(h) %>% select(ef_saz)
  
  y_T <- dados_sem_na[nrow(dados_sem_na),"tend"]
  slope <- I((y_T - dados_sem_na[1,"tend"])/(nrow(dados_sem_na)-1))
  retornar <- rep(y_T,h)
  somar <- (1:h)
  somar <- somar*slope
  tend_pred <- data.frame("y" = retornar+somar)
  
  return(tend_pred+s_hat)
}

decomposicao_multiplicativa <- function(dados, mMM, n_saz, y,h){
  #mMM é o período das médias móveis
  # nsaz é o período sazonal considerado
  # y é o index da variável resposta
  dados["y"] <- dados[y]
  Tend <- rep(NA, length.out = nrow(dados))
  if(mMM%%2 == 0){
    k <- mMM/2
    # se for par
    for(i in (k+1):(nrow(dados)-k)){
      Tend[i] <- (dados[i-k,"y"]+dados[i+k,"y"])/(2*mMM)+sum(dados[(i-k+1):(i+k-1),"y"])/mMM
      Tend <- do.call(rbind,Tend)
      
    }
  }else{
    # mMM ímpar
    k <- (mMM-1)/2
    # se for par
    for(i in (k+1):(nrow(dados)-k)){
      Tend[[i]] <- sum(dados[(i-k):(i+k),"y"])/mMM
    }
  }
  if(nrow(dados)%%n_saz == 0){
    saz_aux <- rep(1:n_saz, nrow(dados)%/%n_saz)
  }else{
    saz_aux <-c(rep(1:n_saz, nrow(dados)%/%n_saz),1:(nrow(dados)%%n_saz))
  }
  dados <- data.frame("y" = dados["y"], "tend" = Tend, "saz" = saz_aux, "y_st" = dados["y"]/Tend)
  colnames(dados) <- c(y, "tend", "saz", "y_st")
  sazon <- dados %>% group_by(saz) %>% summarise('ef_saz' = mean(y_st, na.rm = T))
  sazon$ef_saz <- sazon$ef_saz/mean(sazon$ef_saz)
  dados <- inner_join(dados, sazon, by = "saz") %>% mutate(R = y_st/ef_saz)
  # Predição
  dados_sem_na <- dados %>% filter(!is.na(tend))
  saz_predizer <- rep(dados[nrow(dados),"saz"],h)
  saz_predizer <- saz_predizer +1:h
  saz_predizer <- saz_predizer%%n_saz
  s_hat <- dados_sem_na %>% filter(saz %in% saz_predizer) %>% tail(h) %>% select(ef_saz)
  
  y_T <- dados_sem_na[nrow(dados_sem_na),"tend"]
  slope <- I((y_T - dados_sem_na[1,"tend"])/(nrow(dados_sem_na)-1))
  retornar <- rep(y_T,h)
  somar <- (1:h)
  somar <- somar*slope
  tend_pred <- data.frame("y" = retornar+somar)
  
  return(tend_pred*s_hat)
  
}

naive_sazonal <-  function(dados, y,n_saz,h){
  dados["y"] <- dados[y]
  if(nrow(dados)%%n_saz == 0){
    saz_aux <- rep(1:n_saz, nrow(dados)%/%n_saz)
  }else{
    saz_aux <-c(rep(1:n_saz, nrow(dados)%/%n_saz),1:(nrow(dados)%%n_saz))
  }
  dados["saz"] <- saz_aux
  ultima_saz <- I(dados[nrow(dados), "saz"])[[1]]
  pred_saz <- rep(ultima_saz,h)+1:h
  pred_saz <- data.frame("saz" = matrix(pred_saz, nrow=5))
  pred_saz <- pred_saz %>% mutate("saz" = saz%%n_saz)

  return(I(dados %>% filter(saz %in% I(pred_saz)$saz) %>% tail(h))["y"])
}

tendencia_e_saz <- function(dados, y, p, n_saz, h){
  dados["y"] <- dados[y]
  dados["t"] <- 1:nrow(dados)
  if(nrow(dados)%%n_saz == 0){
    saz_aux <- rep(1:n_saz, nrow(dados)%/%n_saz)
  }else{
    saz_aux <-c(rep(1:n_saz, nrow(dados)%/%n_saz),1:(nrow(dados)%%n_saz))
  }
  dados["saz"] <- saz_aux
  if(p==0){
    modelo <- "y ~ 1"
  }else{
  modelo <- "y ~ t"
  }
  if(p>1){
    for(i in 1:p){
      if(i ==1){next}
      modelo <- paste0(modelo, "+ I(t^",i,")")
    }
  }
    modelo <- paste0(modelo,"+ I(factor(saz))")
    modelo_adj <- lm(as.formula(modelo), dados)
    ultima_saz <- I(dados[nrow(dados), "saz"])[[1]]
    pred_saz <- rep(ultima_saz,h)+1:h
    pred_saz <- data.frame("saz" = matrix(pred_saz, nrow=5))
    pred_saz <- pred_saz %>% mutate("saz" = saz%%n_saz+1)
    predizer <- rep(nrow(dados),h)
    predizer <- predizer+1:h
    df_predizer <- data.frame(t = predizer, "saz" = pred_saz)
    colnames(df_predizer) <- c("t", "saz")
    return(list(data.frame("y" = predict(modelo_adj,df_predizer)), modelo_adj))
}
```

```{r}
#### MILAGRE ###############################################################################
gen_rows = function(n, names, modelo){
  names_param = modelo
  if(modelo != "ARMA_GARCH"){
    string = paste0("column(width = 2, numericInput('", names_param, 1:n,"', '",
                    names,"', value = 0, min = 0))", collapse = ",")
  }
  else{
    string = paste0("column(width = 2, numericInput('", names_param, 1:n,"', '",
                    names,"', value = 0, min = 0))", collapse = ",")
    string = paste0(string, ", column(width = 2, radioButtons('dist', label = h3('Distribuição'),
                    choices = list('Normal' =  1, 'T-student' = 2), selected = 1))")
  }
  style = paste0("color: ", cores[10], "; background-color:", cores[9], "; border-color:", cores[11])
  string = paste0("tagList(fluidRow(", string, ",
                  actionButton('action', label = 'Avaliar Modelo', style = '", style, "')))")
  x = eval(parse(text = string))
  return(x)
}
```

```{r}
#### FUNÇÕES DOS GRAFICOS ##################################################################

get_prev_model = function(dados, modelo, params, distribution = "norm", h = 5){
    sequencia = seq(from = max(dados$date)+1, by = 1, length.out = 5)
    dados = na.omit(dados)
    dados$index = 1:nrow(dados)

    ts_df = as_tsibble(dados, index = index)
    
    if(modelo == "ARIMA"){
      modelo = arima(dados$ret_adjusted, order = params)
      prev = predict(modelo, n.ahead = h)
      prev = as.data.frame(prev)
      prev$index= sequencia
      colnames(prev) = c("Retorno", "Desvio padrão", "idx")
        
    } else if(modelo == "ARMA_GARCH"){
      spec = ugarchspec(mean.model = list(armaOrder = params[1:2],
                                          include.mean = FALSE),
                        variance.model = list(model = 'sGARCH', garchOrder = params[3:4]),
                        distribution.model = distribution)
      modelo =  ugarchfit(spec, dados$ret_adjusted, solver = 'hybrid')
      
      prev = ugarchforecast(modelo, n.ahead = h)
      prev = cbind(prev@forecast$seriesFor, prev@forecast$sigmaFor)
      rownames(prev) = NULL
      prev = as.data.frame(prev)
      prev$index= sequencia
      colnames(prev) = c("Retorno", "Desvio padrão", "idx")
      modelo =  ugarchfit(spec, dados$ret_adjusted, solver = 'hybrid')@fit
      print(distribution)
    
    } else if(modelo == "DEC_AD"){
      n_saz = params[1]
      modelo <- decompose(ts(dados$ret_adjusted, frequency = n_saz),
                          type = "additive")
      modelo$residuals <- na.omit(modelo$random)
      #prev = decomposicao_aditiva(dados, mMM, n_saz, "ret_adjusted", h = h)
      prev <- NA
    } else if(modelo == "DEC_M"){
      n_saz = params[1]
      modelo <- decompose(ts(dados$ret_adjusted, frequency = n_saz),
                          type = "multiplicative")
      modelo$residuals <- na.omit(modelo$random)
      #prev = decomposicao_multiplicativa(dados, mMM, n_saz, "ret_adjusted", h = h)
      prev <- NA
    } else if(modelo == "MEAN"){
      prev = rep(mean(dados$ret_adjusted, h))
      #############3 inclui a linha de baixo
      modelo <- data.frame("residuals" =
                             dados$ret_adjusted-mean(dados$ret_adjusted))
    } else if(modelo == "MEDIAN"){
      prev = rep(median(dados$ret_adjusted, h))
      #############3 inclui a linha de baixo
      modelo <- data.frame("residuals" =
                             dados$ret_adjusted-mean(dados$ret_adjusted))
    } else if(modelo == "NAIVE"){
      prev = rep(dados$ret_adjusted[nrow(dados)], h)
      #############3 inclui a linha de baixo
      modelo <- data.frame("residuals" = 
                             dados$ret_adjusted-lag(dados$ret_adjusted)) %>%
        na.omit()
    } else if(modelo == "SNAIVE"){
      n_saz = params[1]
      prev = naive_sazonal(dados, "ret_adjusted", n_saz, h)
      modelo <- data.frame("residuals" = 
                             dados$ret_adjusted-lag(dados$ret_adjusted, n_saz)) %>%
        na.omit()
    } else if(modelo == "DRIFT"){
      y_T <- dados$ret_adjusted[nrow(dados)]
      slope <- I((y_T - dados$ret_adjusted[1])/(nrow(dados)-1))[[1]]
      retornar <- rep(y_T,h)
      somar <- (1:h)
      somar <- somar*slope
      prev <- data.frame("y" = retornar+somar)
      dados$idx <- 1:nrow(dados)
      modelo <- data.frame("residuals" = 
                             dados$ret_adjusted-
                             (dados$ret_adjusted[1])+slope*(dados$idx-1)) %>%
        na.omit()
    } else if(modelo == "REG_T"){
      p = params[1]
      formula <-  "ret_adjusted ~ index"
      if(p>1){
        for(i in 1:p){
          if(i == 1){next}
          formula <- paste0(formula, "+ I(index^",i,")")
        }
      }
      modelo <- lm(formula, dados)
      prev = predict(modelo, newdata = data.frame(index = nrow(dados)+1:h))
        
    } else if(modelo == "REG_S"){
      n_saz = params[1]
      res <- tendencia_e_saz(dados, y = "ret_adjusted", p=0,n_saz=n_saz, h=h)
      prev <- res[[1]]
      modelo <- res[[2]]
    }  else if(modelo == "REG_TS"){
      p = params[1]
      n_saz = params[2]
      res <- tendencia_e_saz(dados, y = "ret_adjusted", p=p,n_saz=n_saz, h=h)
      prev <- res[[1]]
      modelo <- res[[2]]
    } else if(modelo == "SE"){
      erro <- as.character(params[1])
      tend <- as.character(params[2])
      saz # tem q atribuir
      n_saz # tem q atribuir
      
      modelo <- ets(ts(dados$ret_adjusted, frequency = n_saz),
                    model = str_c(erro, tend, saz))
      prev <- forecast(modelo, h = h)
    }
    return(list(prev, modelo))
}
modelos = c("ARIMA", "ARMA_GARCH", "DEC_AD", "DEC_M", "MEAN", "MEDIAN", "NAIVE", "SNAIVE",
              "DRIFT", "REG_T", "REG_S", "REG_TS", "SE")
  
lista_params = list(c("AR", "I", "MA"), c("AR", "MA", "GARCH 1", "GARCH 2"), c("Sazonalidade"),
                    c("Sazonalidade"), c(), c(), c(), c("Sazonalidade"), c(),
                    c("P"), c("Sazonalidade"), c("P", "Sazonalidade"), c("Erro", "Trend"))
```

```{r include=FALSE}
#### CHUNK DOS GRAFICOS ######
##############################

##adicionei o tamanho dos textos e titulos nos graficos com o "meu_tema"

meu_tema <- theme(panel.background = element_rect(fill = "#3A3A3A"),
        plot.background = element_rect(fill = "#3A3A3A"),
        panel.grid.minor = element_line(color = "#3A3A3A"),
        panel.grid.major = element_line(color = "#3A3A3A"),
        axis.text = element_text(color = "white", size = 12),
        axis.title = element_text(color = "white", size = 12), 
        axis.line = element_line(color = "white"),
        plot.title = element_text(color = "white", hjust = 0.5) 
        )

#### CONSEGUIR GRAFICOS DE DIAGNOSTICO DO MODELO ########################################################
get_graph_model = function(dados, modelo, params, distribution = "norm", h = 5){
  
  infos = get_prev_model(dados = dados, modelo = modelo, params = params,
                         distribution = distribution, h = h)
  prev = infos[[1]]
  modelo = infos[[2]]
  residuos = modelo$residuals  
  aux <- data.frame(idx = 1:length(residuos),
                    res = residuos)
  
  plot_seq <- ggplot(aux, aes(x = idx, y = res))+
    geom_line(color = "#33C481")+
    geom_point(color = "#33C481")+
    geom_hline(aes(yintercept = 0),
               color = "white", linetype =2)+
    labs(title = "Gráfico de Sequência dos Resíduos")+
    theme_bw()+
    meu_tema
  
  acf <- acf(aux$res, plot = F) 
  acf <- data.frame(idx = factor(seq(1,length(acf$acf[,,1]))),
                    acf = acf$acf[,,1])
  acf <- ggplot(acf)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=acf),
                     color = "white", size = 1)+
    geom_hline(aes(yintercept = 0), color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),
               aes(yintercept = 1.96/sqrt(nrow)), 
               color = "#33C481", linetype = 2)+
    geom_hline(data = data.frame(nrow = nrow(dados)),
               aes(yintercept = -1.96/sqrt(nrow)), 
               color = "#33C481",linetype = 2)+
    labs(title = "ACF dos Resíduos")+
    theme_bw()+
    meu_tema+ 
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  acf2 <- acf(aux$res^2, plot = F)
  acf2 <- data.frame(idx = factor(seq(1,length(acf2$acf[,,1]))),
                     acf = acf2$acf[,,1])
  acf2 <- ggplot(acf2)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=acf),
                     color = "white", size = 1)+
    geom_hline(aes(yintercept = 0), color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),
               aes(yintercept = 1.96/sqrt(nrow)), 
               color = "#33C481", linetype = 2)+
    geom_hline(data = data.frame(nrow = nrow(dados)),
               aes(yintercept = -1.96/sqrt(nrow)), 
               color = "#33C481",linetype = 2)+
    labs(title = "ACF dos Resíduos ao Quadrado")+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  pacf <- pacf(aux$res, plot = F)
  pacf <- data.frame(idx = factor(seq(1,length(pacf$acf[,,1]))),
                    pacf = pacf$acf[,,1])
  pacf <- ggplot(pacf)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=pacf),
                 color = "white")+
    geom_hline(aes(yintercept = 0),color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)),
               color = "#33C481",linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)),
                 color = "#33C481", linetype = 2)+
    labs(title = "PACF dos Resíduos")+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))

  if(distribution == "norm"){
    qqplot <- ggplot(aux, aes(sample = res))+
      geom_qq(color = "white")+
      geom_qq_line(color = "#33C481")+
      labs(title = "QQplot do Resíduo (Normal)")+
      theme_bw()+
      meu_tema
    }
  if(distribution == "std"){
    qqplot <- ggplot(aux, aes(sample = res))+
      geom_qq(distribution = qdist, dparams = c(distribution = "std",
                  mu = mean(aux$res, na.rm = T),
                  sigma = sd(aux$res, na.rm = T),
                  skew = 0, shape = coef(modelo)["shape"]),
              color = "white")+
      geom_qq_line(distribution = qdist, dparams = c(distribution = "std",
                  mu = mean(aux$res),
                  sigma = sd(aux$res),
                  skew = 0, shape = coef(modelo)["shape"]),
                   color = "#33C481")+
      labs(title = "QQplot do Resíduo (t-Student)")+
      theme_bw()+
      meu_tema
    }
  
  hist_res <- ggplot(aux, aes(x = res))+
    geom_histogram(fill = "white")+
    labs(title = "Histograma do Resíduo (Normal)")+
    meu_tema
  
  layoutgraf <- plot_layout(
    widths = c(1,1,1),
    heights = c(6,5,8)
  )
  
  # plot(x,y, main = main, xlab = xlab, ylab = ylab, cex = 0.7)
  # qqDist(y = zseries, dist = distribution, lambda = ghlambda, skew = skew, shape = shape)
  
  plot_grid <- (plot_seq)/(qqplot)/(acf+acf2+pacf)+layoutgraf
  return(plot(plot_grid))
}

#### GRAFICOS ACF, PACF, SAZONAL E DA PROPRIA SERIE (NORMAL E RETORNOS)################################################
if(!exists("dados")){
  dados = get_data()
  plot = get_graph_main(dados)
  acf <- acf(dados$adjusted)
  acf <- data.frame(idx = factor(seq(1,length(acf$acf[,,1]))),
                    acf = acf$acf[,,1])
  acf <- ggplot(acf)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=acf),
                 color = "white")+
    geom_hline(aes(yintercept = 0),color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)), 
               color = "#33C481",linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)),
                 color = "#33C481",linetype = 2)+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  pacf <- pacf(dados$adjusted)
  pacf <- data.frame(idx = factor(seq(1,length(pacf$acf[,,1]))),
                    pacf = pacf$acf[,,1])
  pacf <- ggplot(pacf)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=pacf),
                 color = "white")+
    geom_hline(aes(yintercept = 0),color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)),
               color = "#33C481",linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)),
                 color = "#33C481", linetype = 2)+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  plot_r = get_graph_main(dados, "ret")
  acf_r <- acf(dados$ret_adjusted)
  acf_r <- data.frame(idx = factor(seq(1,length(acf_r$acf[,,1]))),
                    acf_r = acf_r$acf[,,1])
  acf_r <- ggplot(acf_r)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=acf_r), color = "white")+
    geom_hline(aes(yintercept = 0), color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)),
               color = "#33C481", linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)), 
                 color = "#33C481",linetype = 2)+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  acf2_r <- acf(dados$ret_adjusted^2)
  acf2_r <- data.frame(idx = factor(seq(1,length(acf2_r$acf[,,1]))),
                    acf_r = acf2_r$acf[,,1])
  acf2_r <- ggplot(acf2_r)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=acf_r),
                 color = "white")+
    geom_hline(aes(yintercept = 0),color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)), color = "#33C481", linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)), color = "#33C481", linetype = 2)+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
  
  pacf_r <- pacf(dados$ret_adjusted)
  pacf_r <- data.frame(idx = factor(seq(1,length(pacf_r$acf[,,1]))),
                    pacf = pacf_r$acf[,,1])
  pacf_r <- ggplot(pacf_r)+
    geom_segment(aes(x = idx, xend = idx, y = 0, yend=pacf),
                 color = "white")+
    geom_hline(aes(yintercept = 0),color = "white")+
    geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = 1.96/sqrt(nrow)), color = "#33C481", linetype = 2)+
      geom_hline(data = data.frame(nrow = nrow(dados)),aes(yintercept = -1.96/sqrt(nrow)), color = "#33C481", linetype = 2)+
    theme_bw()+
    meu_tema+
    scale_x_discrete(breaks = seq(0,35, by=5))
}
```

```{r}
#### MUDAR AS CORES DO DASHBOARD ##################################
cores = c("#21A366", "#21A366", "#21A366", "#185C37", "#10793F",
          "#10793F", "#185C37", "#10793F", "#3A3A3A", "white", "#33c481", "#737373")

###Ignore
tosupress = paste0("a#ui-tab-",1:1000, collapse = ", ")

# cinza microsoft "#737373"
# cinza xbox "#3A3A3A"
# azul1 "#41A5EE"
# azul2 "#2B7CD3"
# azul3 "#1B5EBE"
# azul4 "#103F91"
# verde xbox "#107C10"
# verde1 "#33C481"
# verde2 "#21A366"
# verde3 "#10793F"
# verde4 "#185C37"

#Lista das cores:
#1 - cor atrás do titulo
#2 - cor atrás do titulo quando voce passa o mouse
#3 - barra do lado de cima
#4 - cor da barra do menu na esquerda
#5 - aba ativa no menu da esquerda
#6 - abas nao-ativas no menu da esquerda
#7 - abas da esquerda quando se passa o mouse (ativas)
#8 - abas da esquerda quando se passa o mouse (nao ativas)
#9 - fundo da parte principal, onde ficam os codigos
#10- cor da fonte da pagina


#EXISTE UMA CHANCE NÃO-NULA DE QUE,
#AO MUDAR QUALQUER LINHA DA FUNÇÃO ABAIXO,
#SEU COMPUTADOR EXPLODA

back_color <- paste0("
$(document).ready(function() {
  // Definir a cor de fundo padrão para todos os botões de rádio e os elementos btn, btn-default, action-button e shiny-bound-input
  $('input:radio[name=modelo_nome], .btn, .btn-default, .action-button, .shiny-bound-input').parent().css({
    'background-color': '", cores[9], "',
    'color': '", cores[10], "',
    'border-color': '", cores[11], "'
  });

  // Lidar com a mudança do botão de rádio selecionado
  $(document).on('change', 'input:radio[name=modelo_nome]', function() {
    // Limpar todas as classes 'active-btn' e restaurar a cor de fundo padrão
    $('input:radio[name=modelo_nome], .btn, .btn-default, .action-button, .shiny-bound-input').parent().removeClass('active-btn').css({
      'background-color': '", cores[9], "',
      'color': '", cores[10], "',
      'border-color': '", cores[11], "'
    });

    // Obter o botão de rádio selecionado e atualizar sua cor de fundo
    var selectedBtn = $('input:radio[name=modelo_nome]:checked');
    selectedBtn.parent().addClass('active-btn').css({
      'background-color': '", cores[11], "',
      'color': '", cores[10], "',
      'border-color': '", cores[11], "'
    });
  });

  // Verificar se algum botão de rádio já está selecionado no carregamento da página
  var selectedBtn = $('input:radio[name=modelo_nome]:checked');
  if (selectedBtn.length > 0) {
    selectedBtn.parent().addClass('active-btn').css({
      'background-color': '", cores[11], "',
      'color': '", cores[10], "',
      'border-color': '", cores[11], "'
    });
  }
});
")


color_buttons <- tags$script(HTML(back_color))


#### CODIGO EM CSS PARA MUDAR AS CORES #########################################################
aplica_tema = tags$head(tags$style(HTML(glue(.trim = FALSE, .open = " <", .close = " >", '

/* COR ATRAS DO TITULO DO TRABALHO */
.skin-blue .main-header .logo {
    background-color:  <cores[1] >;
    color: white;}
    
/* COR ATRAS DO TITULO DO TRABALHO QUANDO VOCE PASSA O MOUSE */
.skin-blue .main-header .logo:hover {
    background-color:  <cores[2] >;
    color: white;}
    
/* BARRA DO LADO DE CIMA */
.skin-blue .main-header .navbar {
    background-color:  <cores[3] >;}
    
/* COR DA BARRA DO MENU NA ESQUERDA */
.skin-blue .main-sidebar {
    background-color:  <cores[4] >;}
    
/* ABA ATIVA NO MENU DA ESQUERDA */
.skin-blue .main-sidebar .sidebar .sidebar-menu .active a {
    background-color:  <cores[5] >;}
    
/* ABAS QUE NAO ESTÃO ATIVAS NO MENU DA ESQUERDA */
.skin-blue .main-sidebar .sidebar .sidebar-menu a {
    background-color:  <cores[6] >;}
    
/* PASSAR O MOUSE NO MENU QUE FICA DO LADO ESQUERDO (ABAS QUE ESTAO ATIVAS)*/
.skin-blue .main-sidebar .sidebar .sidebar-menu a:hover {
    background-color:  <cores[7] >;}
    
/* PASSAR O MOUSE NO MENU QUE FICA DO LADO ESQUERDA (ABAS QUE NÃO ESTÃO ATIVAS) */
.skin-blue .main-header .navbar .sidebar-toggle:hover {
    background-color:  <cores[8] >;}
    
/* CORPO DO DASHBOARD (LUGAR ONDE FICA OS GRAFICOS) */
.content-wrapper,
.right-side {
    background-color:  <cores[9] >;}
    
/* FONTES, SE FOR MUDAR, MUDA TUDO DE UMA VEZ */
.content-wrapper,
.right-side, * {
    color:  <cores[10] >;}
.content-wrapper,
.right-side, h1, h2, h3, h4, h5,
.c1, .c2, .c3, .c4, .c5, .c6,
.c7, .c8, .c9, .c10, .active{
    color:  <cores[10] > !important;}
.content-wrapper,
.right-side,  <tosupress >{
    color:  <cores[11] >;}
.nav > li > a:focus, .nav > li > a:hover {
    color:  <cores[9] >;
    background-color:  <cores[9] >;}
.nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover {
    color:  <cores[9] >;
    background-color:  <cores[9] >;}

.shiny-notification-error {
    background-color: <cores[11] >;
    color: <cores[9] >;}
    .shiny-notification-message {
    background-color: <cores[11] >;
    color: <cores[9] >;}

/* RAPOSO, NÃO TOQUE! */
.form-control {
    border: 3px;
    width: 50% !important;
    height: 200%;
    border-color:  <cores[11] > !important;
    background-color:  <cores[12] >;
    color:  <cores[9] >}

.content-wrapper,
.right-side, .dygraph-legend{
    background-color:  <cores[9] > !important;}
.container-fluid{
    background-color:  <cores[9] > !important;}'))))
```

```{r}
#### ABAS DE TEXTO #######################################
tab_titulo <- includeHTML("textos/titulo.html")

tab_introducao <- column(12,
                         h1("Introdução"),
                         h3("Um grupo de investidores está interessado em diversificar os segmentos de mercado nos quais investem. Para isso, eles procuraram o nosso grupo de estudantes Séries Temporais (ME607) da Unicamp a fim de obter um modelo capaz de capturar a dinâmica dos preços de retorno das ações da Microsoft na Bolsa de Valores de São Paulo (BOVESPA), cujo código é MSFT34.SA, desde 01/01/2013."),
                         h3("Para isso, inicialmente, foi feita uma análise exploratória dos preços de fechamento e dos retornos através de gráficos sequenciais e das funções de autocorrelação e autocorrelação parcial. Na sequência, foram ajustados diversos modelos, os quais passaram por um diagnóstico e, aqueles que capturaram bem a dinâmica dos dados foram comparados a partir de uma validação cruzada via rolling window. Por fim, aquele que obteve a melhor performance foi colocado em produção, sendo utilizado para prever os retornos ao longo de 5 dias."))

tab_contexto <- column(12,
                       h1("Contexto"),
                       h3("O princípio da diversificação afirma que é preciso diversificar a carteira de investimentos, de forma a reduzir riscos e melhorar a probabilidade de obtenção de resultados positivos. Com isso em mente, um grupo de investidores, após realizar um estudo de mercado, concluiu que a Microsoft seria, potencialmente, uma boa empresa para se adquirir ações. Entretanto, a fim de tomar decisões mais assertivas e baseadas em dados, eles contataram o nosso grupo de Séries Temporais (ME607) da Unicamp em busca de um modelo capaz de capturar a dinâmica dos preços dessas ações desde 2013 .
"))

tab_abordagem <- column(12,
                        h1("Abordagem Utilizada"),
                        h3("Considerando a situação apresentada, primeiramente foi realizada uma análise exploratória dos preços ajustados de fechamento das ações, incluindo gráficos sequenciais e das funções de autocorrelação e autocorrelação parcial. Na sequência, o mesmo foi realizado para o preço de retorno ajustado, de forma a tornar possível uma compreensão melhor da série.
"),
                        h3("Em seguida, há um local em que o usuário pode escolher o modelo que deseja tentar ajustar aos dados, o qual apresenta gráficos que apresentam uma análise dos resíduos. Posteriormente, os modelos que foram considerados melhores dentre todos os que foram testados por nós e que passaram pelo diagnóstico foram submetidos a uma validação cruzada com rolling-window, através da qual foi escolhido e retornado o modelo com melhor desempenho.
"))

tab_serie_fechamento <- column(12,
                    h1("Análise exploratória da série de fechamento"),
                    tabsetPanel(
                      tabPanel("Gráfico",
                               h3("O gráfico abaixo apresenta a evolução do preço de fechamento das ações ajustado. Nota-se que havia uma tendência de crescimento forte até janeiro de 2022, seguida de uma queda ocorrida até um ano depois, quando iniciou novamente um período de crescimento."),
                               dygraphOutput("serie_grafico")
                      ),
                      tabPanel("ACF",
                               h3("A função de autocorrelação dos preços ajustados está apresentada abaixo. A partir dela, percebe-se forte tendência, de forma que é fácil ver que a série não é estacionária."),
                               plotOutput("serie_acf")
                      ),
                      tabPanel("PACF",
                               h3("A função de autocorrelação parcial dos preços ajustados é ilustrada abaixo. Com base nela, conclui-se que há uma autocorrelação parcial muito forte com o valor do tempo anterior, de modo que é necessário modelá-la."),
                               plotOutput("serie_pacf")
                      )
                    )
)
#### ABA "SERIE RETORNO" #######################################
tab_serie_retorno <- column(12,
                    h1("Análise exploratória da série de retornos"),
                    tabsetPanel(
                      tabPanel("Gráfico",
                               h3("O gráfico abaixo mostra a evolução histórica dos retornos da série. É possível observar que a média é constante, diferentemente do que ocorre com a variância."),
                               dygraphOutput("serie_grafico_r")
                      ),
                      tabPanel("ACF",
                               h3("Conteúdo da Aba 2"),
                               plotOutput("serie_acf_r")
                      ),
                      tabPanel("ACF dos quadrados dos retornos",
                               h3("Conteúdo da Aba 2"),
                               plotOutput("serie_acf2_r")
                      ),
                      tabPanel("PACF",
                               h3("Conteúdo da Aba 3"),
                               plotOutput("serie_pacf_r")
                      )
                    )
)

#### ABA MODELOS ###############################################
tab_modelos <- column(12,
                      h1("Modelos"),
                      fluidRow(
                        column(12,
                               radioGroupButtons("modelo_nome", h2("Escolha seu modelo"),
                                                choices = list("ARIMA" = 1, "GARCH" = 2, "Decomposição Aditiva" = 3,
                                                               "Decomposição Multiplicativa" = 4, "Média" = 5,
                                                               "Mediana" = 6, "Naive" = 7, "Seasonal Naive" = 8,
                                                               "Drift" = 9, "Regressão T" = 10, "Regressão S" = 11,
                                                               "Regressão TS" = 12, "Suavização Exponencial" = 13),
                                                selected = 1, individual = TRUE,
                                                direction = "horizontal", width = "50%"),
                               color_buttons,
                        )
                      ),
                      h2("Escolha seus parâmetros e Avalie o modelo"),
                      uiOutput("modelo_user"),
                      uiOutput("graficos_user")
                      # Conteúdo do Slide de Modelos aqui
)

#### ABA MODELO ESCOLHIDO ###############################################
tab_modelo_escolhido <- column(12,
                               h1("Modelo Escolhido")
)
#### ABA VALIDAÇÃO ###############################################
tab_validacao <- column(12,
                        h1("Validação"),
                        # Conteúdo do Slide de Validação aqui
)
#### ABA CONCLUSAO ###############################################
tab_conclusao <- column(12,
                        h1("Conclusão"),
                        # Conteúdo do Slide de Conclusão aqui
)
```

```{r}
#### UI DO DASHBOARD EM SHINY ########################################################
ui <- fluidPage(dashboardPage(
  dashboardHeader(title = "Séries Temporais"),
  #### Sidebar ##################################################
  dashboardSidebar(
    sidebarMenu(
      id = "tabs",
      menuItem("Título", tabName = "Título"), ###### inverti a ordem
      menuItem("Introdução", tabName = "Introdução"),
      menuItem("Contexto", tabName = "Contexto"), 
      menuItem("Abordagem", tabName = "Abordagem"), ###### adicionei inves de Explicacao
      menuItem("Série fechamento", tabName = "Série fechamento"),
      menuItem("Série retorno", tabName = "Série retorno"),
      menuItem("Modelos", tabName = "Modelos"),
      menuItem("Modelo Escolhido", tabName = "Modelo Escolhido"),
      menuItem("Validação", tabName = "Validação"),
      menuItem("Conclusão", tabName = "Conclusão")
    )
  ),
  #### Body #####################################################
  dashboardBody(
    aplica_tema,
    tabItems(
      tabItem(tabName = "Título",
              fluidPage(
                fluidRow(
                  tab_titulo
                )
              )
      ),############# inverti a ordem pra atual intro>contex>abordag
      tabItem(tabName = "Introdução",
              fluidPage(
                fluidRow(
                  tab_introducao
                )
              )
      ),
      tabItem(tabName = "Contexto",
              fluidPage(
                fluidRow(
                  tab_contexto
                )
              )
      ),
      tabItem(tabName = "Abordagem",
              fluidPage(
                tab_abordagem
              )
      ),
      tabItem(tabName = "Série fechamento",
              fluidPage(
                fluidRow(
                  tab_serie_fechamento
                )
              )
      ),
      tabItem(tabName = "Série retorno",
              fluidPage(
                fluidRow(
                  tab_serie_retorno
                )
              )
      ),
      tabItem(tabName = "Modelos",
              fluidPage(
                fluidRow(
                  tab_modelos
                )
              )
      ),
      tabItem(tabName = "Modelo Escolhido",
              fluidPage(
                fluidRow(
                  tab_modelo_escolhido
                )
              )
      ),
      tabItem(tabName = "Validação",
              fluidPage(
                fluidRow(
                  tab_validacao
                )
              )
      ),
      tabItem(tabName = "Conclusão",
              fluidPage(
                fluidRow(
                  tab_conclusao
                )
              )
      )
    )
  ),
),
  #### Mover Slide com o teclado #################################
useKeys(),
keysInput("keys", c("left", "right")))
```

```{r}
#### SERVER DO DASHBOARD EM SHINY ##############################################
server <- function(input, output, session) {
  
  ##Gráficos da aba Série Fechamento############################
  output$serie_grafico <- renderDygraph({plot})
  output$serie_acf <- renderPlot({acf})
  output$serie_pacf <- renderPlot({pacf})
  output$serie_sazonal <- renderPlot({saz})
  
  ##Gráficos da aba Série Retorno###############################
  output$serie_grafico_r <- renderDygraph({plot_r})
  output$serie_acf_r <- renderPlot({acf_r})
  output$serie_acf2_r <- renderPlot({acf2_r})
  output$serie_pacf_r <- renderPlot({pacf_r})
  output$serie_sazonal_r <- renderPlot({saz_r})
  
  ##Aba Modelos#################################################
  
  n_params <- reactiveValues()
  totalidade = reactiveValues()
  parametros = reactiveValues()
  paramComp = reactiveValues()
  continue = reactiveValues()
  
  observeEvent(input$action, {
    continue$continue = TRUE
  })
  
  observeEvent(parametros$parametros, {
    continue$continue <- FALSE
  })
  
  output$modelo_user <- renderUI({
    id <- input$modelo_nome |> as.numeric()
    numero = length(lista_params[[id]])
    n_params$n_params = numero
    continue$continue = FALSE
    
    if(numero == 0){
      continue$continue = TRUE
      return(NULL)
    }
    else{
      inputs <- gen_rows(n_params$n_params, lista_params[[id]], modelos[id])
      return(inputs)
    }
  })
  
  output$graficos_user <- renderUI({
    id <- input$modelo_nome |> as.numeric()
    string = paste0("input$", modelos[id])
    parametros$parametros <- eval(parse(text = paste0("c(",paste0(string, 1:10, collapse = ","), ")"))) |>
      as.numeric() |> na.omit()
    
    totalidade$totalidade <- length(parametros$parametros)
    
    paramComp$paramComp = (totalidade$totalidade == n_params$n_params)
    
    if(paramComp$paramComp){
      graficos_user <- plotOutput("graficos_user_plot")
      return(graficos_user)
    }
    return(NULL)
  })
  
  output$graficos_user_plot <- renderPlot({
    id <- input$modelo_nome |> as.numeric()
    param = parametros$parametros |> as.numeric()
    req(continue$continue)
    if(paramComp$paramComp){
      modelo = modelos[id]
      dist = "norm"
      if(id == 2){
        if(input$dist != 1){
          modelo = modelos[id]
          dist = "std"
        }
      }
      graficos_user <- tryCatch({
        get_graph_model(dados = dados, modelo = modelo, params = param, distribution = dist)
      }, error = function(e){
        showNotification("Erro - Parâmetros em Formato Incorreto \n Tente Novamente.", duration = 2, type = "error")
        return(NULL)
      })
      return(graficos_user)
    }
  })
  
  ##Mover o slide com as setas do teclado#######################
  id_tab = reactiveVal(1)
  observeEvent(input$keys, {
    todas_tabs = c("Título", "Introdução", "Contexto", "Abordagem",
                   "Série fechamento", "Série retorno", "Modelos",
                   "Modelo Escolhido", "Validação", "Conclusão")
    inputado = input$keys
    id = isolate(id_tab())
    if(inputado == "left"){
      if(id > 1){
        id = id - 1
      }
    }
    if(inputado == "right"){
      if(id < length(todas_tabs)){
        id = id + 1
      }
    }
    id_tab(id)
    
    updateTabItems(session, "tabs", selected = todas_tabs[id])
  })
}
```

```{r}
#### GERAR DASHBOARD #######################################
shinyApp(ui = ui, server = server)
```

```{r, echo = FALSE, message = FALSE}
suppressWarnings({
  invisible({
    knitr::purl(input = "Trabalho Final.Rmd", output = "Trabalho Final.R")
    if(x == 0){
      x = 1
      source("Trabalho Final.R")
    }
    file.remove("Trabalho Final.R")
    x = 0
  })
})
shinyApp(ui = ui, server = server)
```





